# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrinterSettings.ui'
#
# Created: Mon Aug 24 21:04:17 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(646, 332)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.AreaLength = QtGui.QLineEdit(Dialog)
        self.AreaLength.setObjectName(_fromUtf8("AreaLength"))
        self.horizontalLayout_6.addWidget(self.AreaLength)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.AreaWidth = QtGui.QLineEdit(Dialog)
        self.AreaWidth.setObjectName(_fromUtf8("AreaWidth"))
        self.horizontalLayout_7.addWidget(self.AreaWidth)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.AreaHeight = QtGui.QLineEdit(Dialog)
        self.AreaHeight.setObjectName(_fromUtf8("AreaHeight"))
        self.horizontalLayout_8.addWidget(self.AreaHeight)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.StepsPerRevolution = QtGui.QLineEdit(Dialog)
        self.StepsPerRevolution.setObjectName(_fromUtf8("StepsPerRevolution"))
        self.horizontalLayout_10.addWidget(self.StepsPerRevolution)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.HeightPerRevolution = QtGui.QLineEdit(Dialog)
        self.HeightPerRevolution.setObjectName(_fromUtf8("HeightPerRevolution"))
        self.horizontalLayout_9.addWidget(self.HeightPerRevolution)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ipAdress = QtGui.QLineEdit(Dialog)
        self.ipAdress.setObjectName(_fromUtf8("ipAdress"))
        self.horizontalLayout_2.addWidget(self.ipAdress)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_12.addWidget(self.checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.illuminationTime = QtGui.QLineEdit(Dialog)
        self.illuminationTime.setObjectName(_fromUtf8("illuminationTime"))
        self.horizontalLayout_3.addWidget(self.illuminationTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.illuminationIntensity = QtGui.QLineEdit(Dialog)
        self.illuminationIntensity.setObjectName(_fromUtf8("illuminationIntensity"))
        self.horizontalLayout_4.addWidget(self.illuminationIntensity)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.PrinterLiquidPrice = QtGui.QLineEdit(Dialog)
        self.PrinterLiquidPrice.setObjectName(_fromUtf8("PrinterLiquidPrice"))
        self.horizontalLayout_5.addWidget(self.PrinterLiquidPrice)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.CancelButton = QtGui.QPushButton(Dialog)
        self.CancelButton.setObjectName(_fromUtf8("CancelButton"))
        self.horizontalLayout.addWidget(self.CancelButton)
        self.OkButton = QtGui.QPushButton(Dialog)
        self.OkButton.setObjectName(_fromUtf8("OkButton"))
        self.horizontalLayout.addWidget(self.OkButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Printing Area Length (cm):", None))
        self.AreaLength.setText(_translate("Dialog", "12", None))
        self.label_2.setText(_translate("Dialog", "Printing Area Width (cm):", None))
        self.AreaWidth.setText(_translate("Dialog", "19", None))
        self.label_3.setText(_translate("Dialog", "Printing Area Height (cm):", None))
        self.AreaHeight.setText(_translate("Dialog", "10", None))
        self.label_11.setText(_translate("Dialog", "Stepper Motor Steps ", None))
        self.label_12.setText(_translate("Dialog", "per Axis Revolution:", None))
        self.StepsPerRevolution.setText(_translate("Dialog", "16", None))
        self.label_9.setText(_translate("Dialog", "Height Difference per ", None))
        self.label_10.setText(_translate("Dialog", "Revolution of Printer Axis (mm):", None))
        self.HeightPerRevolution.setText(_translate("Dialog", "0.8", None))
        self.label_4.setText(_translate("Dialog", "Printer IP adress:", None))
        self.ipAdress.setText(_translate("Dialog", "192.168.2.101", None))
        self.label_13.setText(_translate("Dialog", "Use SSL", None))
        self.label_5.setText(_translate("Dialog", "Illumination time per Slice (s):", None))
        self.illuminationTime.setText(_translate("Dialog", "10", None))
        self.label_7.setText(_translate("Dialog", "Illumination intensity:", None))
        self.illuminationIntensity.setText(_translate("Dialog", "100", None))
        self.label_8.setText(_translate("Dialog", "%", None))
        self.label_6.setText(_translate("Dialog", "Price of Printer Liquid (€/liter):", None))
        self.PrinterLiquidPrice.setText(_translate("Dialog", "900", None))
        self.CancelButton.setText(_translate("Dialog", "Cancel", None))
        self.OkButton.setText(_translate("Dialog", "Ok", None))

